plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.5'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.cricket'
version = '0.0.1-SNAPSHOT'
description = 'Cricket auction project'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	runtimeOnly 'com.microsoft.sqlserver:mssql-jdbc'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.2.0' // Swagger UI
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	compileOnly 'org.projectlombok:lombok:1.18.34' // Use the latest stable version
	annotationProcessor 'org.projectlombok:lombok:1.18.34' // Use the latest stable version
	testCompileOnly 'org.projectlombok:lombok:1.18.34' // For tests if needed
	testAnnotationProcessor 'org.projectlombok:lombok:1.18.34' // For tests if needed
	implementation 'org.springframework.boot:spring-boot-starter-security'

}

tasks.named('test') {
	useJUnitPlatform()
}
