-- ============================================================================
-- Production Data Load Script
-- ============================================================================
-- WARNING:
--   This script loads data only.
--   Run sql-scripts/production/01-SQL_CLEANUP_AUCTION_DATA.sql first if you need a full reset.
--   Run sql-scripts/production/02-SQL_SEED_REFERENCE_MASTER_DATA.sql before this script.
-- Scope:
--   Loads pooled players (playerStatus = 'POOLED') into tblPlayer.
--   Excludes all players already covered in scripts 03 (All Rounders),
--   04 (Bowlers), 05 (Batsmen), and 06 (Wildcards).
--   Excludes team POCs defined in 02-SQL_SEED_REFERENCE_MASTER_DATA.sql.
--
-- Notes:
--   1) playerStats is saved in the agreed JSON structure: matches/runs/strikeRate/Wickets/economy.
--   2) playerStatus is initialized as POOLED.
--   3) isConsiderInAuction is set to 0.
--   4) skillId assigned per player skill:
--        1 = BATSMAN
--        2 = BOWLER
--        3 = ALL_ROUNDER
--   5) groupCode = 'PL-1' for all pooled players.
-- ============================================================================

USE epl_auction;

-- --------------------------------------------------------------------------
-- Step 1: Load pooled players
-- --------------------------------------------------------------------------
INSERT INTO tblPlayer (
    playerName,
    skillId,
    photo,
    description,
    basePrice,
    playerStatus,
    playerStats,
    isNewPlayer,
    tournamentId,
    isConsiderInAuction,
    groupCode
) VALUES
(
    'Vishal Ganpat Gaikwad',
    2,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":2,"runs":1,"strikeRate":50.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Gavhane Uddhav',
    3,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":2,"runs":3,"strikeRate":27.27,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Shubham Patil',
    3,
    NULL,
    'Utility All-Rounder (118 Runs, 9 Wkts)',
    4000,
    'POOLED',
    '{"matches":22,"runs":118,"strikeRate":128.26,"Wickets":9,"economy":10.48}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Deepak Jadhav',
    3,
    NULL,
    'Strike All-Rounder (13 Wkts, Eco 5.67)',
    4000,
    'POOLED',
    '{"matches":13,"runs":30,"strikeRate":60.00,"Wickets":13,"economy":5.67}',
    0,
    1,
    0,
    'PL-1'
),
(
    'VIPIN RATHORE',
    1,
    NULL,
    'Attacking Batter (174 Runs)',
    4000,
    'POOLED',
    '{"matches":11,"runs":174,"strikeRate":119.18,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Omprakash Shewale',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":6,"runs":14,"strikeRate":93.33,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Sandeep Maske',
    3,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":1,"runs":1,"strikeRate":11.11,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Abhishek Nishad',
    3,
    NULL,
    'Utility All-Rounder (7 Wkts in 7 Matches)',
    4000,
    'POOLED',
    '{"matches":7,"runs":44,"strikeRate":141.94,"Wickets":7,"economy":12.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Pramod Bavchikar',
    1,
    NULL,
    'Attacking Batter (109 Runs, SR 132.93)',
    4000,
    'POOLED',
    '{"matches":15,"runs":109,"strikeRate":132.93,"Wickets":7,"economy":8.05}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Kalpesh Soni',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":4,"runs":27,"strikeRate":135.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Gourav Nagar',
    3,
    NULL,
    'Utility All-Rounder (4 Wkts, Eco 7.54)',
    4000,
    'POOLED',
    '{"matches":9,"runs":45,"strikeRate":91.84,"Wickets":4,"economy":7.54}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Varun Rajwade',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":4,"runs":22,"strikeRate":157.14,"Wickets":1,"economy":17.50}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Ujval Mehta',
    3,
    NULL,
    'Utility All-Rounder (200 Runs, 14 Wkts, Eco 7.47)',
    4000,
    'POOLED',
    '{"matches":37,"runs":200,"strikeRate":122.70,"Wickets":14,"economy":7.47}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Naveen',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":10,"runs":51,"strikeRate":87.93,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'vaibhav vyas',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":6,"runs":46,"strikeRate":92.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Ajinkya ANIL Gharapurkar',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":7,"runs":56,"strikeRate":121.74,"Wickets":1,"economy":22.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Santanu Ghosh',
    1,
    NULL,
    'Steady Middle-Order Batter (205 Runs)',
    4000,
    'POOLED',
    '{"matches":21,"runs":205,"strikeRate":113.26,"Wickets":1,"economy":16.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Atharva Dharmik',
    3,
    NULL,
    'Utility All-Rounder (2 Wkts in 6 Matches)',
    4000,
    'POOLED',
    '{"matches":6,"runs":24,"strikeRate":66.67,"Wickets":2,"economy":10.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Harikesh Prajapati',
    3,
    NULL,
    'Utility All-Rounder (2 Wkts, Eco 8.00)',
    4000,
    'POOLED',
    '{"matches":5,"runs":4,"strikeRate":26.67,"Wickets":2,"economy":8.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Praful Dhawale',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":1,"runs":11,"strikeRate":157.14,"Wickets":0,"economy":16.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Abasaheb Sangale',
    3,
    NULL,
    'Useful Wicket-Taker (11 Wkts)',
    4000,
    'POOLED',
    '{"matches":29,"runs":49,"strikeRate":80.33,"Wickets":11,"economy":10.61}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Tejas Modi',
    3,
    NULL,
    'Consistent All-Rounder (435 Runs, 17 Wkts)',
    4000,
    'POOLED',
    '{"matches":41,"runs":435,"strikeRate":123.93,"Wickets":17,"economy":9.91}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Amol Ikhe',
    1,
    NULL,
    'Utility Batter (131 Runs)',
    4000,
    'POOLED',
    '{"matches":39,"runs":131,"strikeRate":84.52,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Pankaj Soun',
    3,
    NULL,
    'Utility All-Rounder (5 Wkts)',
    4000,
    'POOLED',
    '{"matches":13,"runs":53,"strikeRate":115.22,"Wickets":5,"economy":9.33}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Ratnadip Kore',
    1,
    NULL,
    'Quick Scorer (SR 135.11)',
    4000,
    'POOLED',
    '{"matches":9,"runs":127,"strikeRate":135.11,"Wickets":0,"economy":16.33}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Shubham Sulke',
    1,
    NULL,
    'Steady Top-Order Batter (239 Runs)',
    4000,
    'POOLED',
    '{"matches":27,"runs":239,"strikeRate":118.32,"Wickets":1,"economy":11.80}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Gopi Bodhankar',
    3,
    NULL,
    'Utility All-Rounder (179 Runs, 8 Wkts, Eco 8.45)',
    4000,
    'POOLED',
    '{"matches":37,"runs":179,"strikeRate":96.24,"Wickets":8,"economy":8.45}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Rafiq',
    2,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":8,"runs":33,"strikeRate":76.74,"Wickets":1,"economy":12.29}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Shubham Deokate',
    3,
    NULL,
    'Quick Scorer with Useful Bowling (160 Runs, 5 Wkts, SR 144.14)',
    4000,
    'POOLED',
    '{"matches":10,"runs":160,"strikeRate":144.14,"Wickets":5,"economy":8.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'suraj salunkhe',
    3,
    NULL,
    'Strike Bowler (13 Wkts)',
    4000,
    'POOLED',
    '{"matches":25,"runs":18,"strikeRate":75.00,"Wickets":13,"economy":11.34}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Kiran khade',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":6,"runs":32,"strikeRate":114.29,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Shailesh Wagh',
    3,
    NULL,
    'Consistent Batter with Bowling Support (520 Runs, 8 Wkts)',
    4000,
    'POOLED',
    '{"matches":39,"runs":520,"strikeRate":143.65,"Wickets":8,"economy":11.17}',
    0,
    1,
    0,
    'PL-1'
),
(
    'chetan keskar',
    3,
    NULL,
    'Utility All-Rounder (245 Runs, 8 Wkts)',
    4000,
    'POOLED',
    '{"matches":69,"runs":245,"strikeRate":80.86,"Wickets":8,"economy":10.38}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Pavan Zalani',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":9,"runs":90,"strikeRate":126.76,"Wickets":2,"economy":15.14}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Sushant Rathod',
    3,
    NULL,
    'Utility All-Rounder (2 Wkts in 1 Match)',
    4000,
    'POOLED',
    '{"matches":1,"runs":15,"strikeRate":150.00,"Wickets":2,"economy":8.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Abhishek Shrivastava',
    1,
    NULL,
    'Explosive Scorer (SR 196.00)',
    4000,
    'POOLED',
    '{"matches":6,"runs":147,"strikeRate":196.00,"Wickets":2,"economy":6.33}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Pavan Marmat',
    3,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":7,"runs":26,"strikeRate":92.86,"Wickets":3,"economy":11.75}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Prasad khanderai (VC)',
    3,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":4,"runs":18,"strikeRate":66.67,"Wickets":2,"economy":9.50}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Pratik Agrawal',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":4,"runs":6,"strikeRate":60.00,"Wickets":1,"economy":10.50}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Suraj Sonawane',
    3,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":5,"runs":5,"strikeRate":62.50,"Wickets":2,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Rohan Chitambare',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":9,"runs":43,"strikeRate":113.16,"Wickets":2,"economy":8.53}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Piyush sandhan',
    3,
    NULL,
    'Utility All-Rounder (2 Wkts in 5 Matches)',
    4000,
    'POOLED',
    '{"matches":5,"runs":7,"strikeRate":36.84,"Wickets":2,"economy":8.20}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Rupesh Suryawanshi',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":7,"runs":33,"strikeRate":117.86,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Anuj Bande',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":7,"runs":77,"strikeRate":118.46,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'MS Sayyad',
    1,
    NULL,
    'High Strike-Rate Batter (SR 159.09)',
    4000,
    'POOLED',
    '{"matches":12,"runs":35,"strikeRate":159.09,"Wickets":0,"economy":7.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Omkar Dnyanmote',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":13,"runs":105,"strikeRate":120.69,"Wickets":1,"economy":8.33}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Manish Khade',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":14,"runs":30,"strikeRate":62.50,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Akshay Thosar',
    3,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":8,"runs":20,"strikeRate":105.26,"Wickets":1,"economy":13.78}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Diwakar Barde',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":6,"runs":19,"strikeRate":67.86,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Nikhil Jogdand',
    3,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":11,"runs":22,"strikeRate":100.00,"Wickets":0,"economy":10.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Akshay Pujari',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":3,"runs":19,"strikeRate":105.56,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Yatharth Mishra',
    2,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":15,"runs":8,"strikeRate":50.00,"Wickets":0,"economy":13.55}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Gopal Pawar',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":5,"runs":38,"strikeRate":97.44,"Wickets":0,"economy":16.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Nilesh Deshmukh',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":1,"runs":8,"strikeRate":57.14,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Virendra Panpatil',
    2,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":6,"runs":16,"strikeRate":69.57,"Wickets":1,"economy":10.50}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Abhijeet Deshmukh',
    1,
    NULL,
    'Quick Scorer (153 Runs, SR 141.67)',
    4000,
    'POOLED',
    '{"matches":19,"runs":153,"strikeRate":141.67,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Swapnil Patil',
    3,
    NULL,
    'Explosive Batter (SR 205.95)',
    4000,
    'POOLED',
    '{"matches":5,"runs":173,"strikeRate":205.95,"Wickets":1,"economy":18.80}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Zeeshan Ali',
    3,
    NULL,
    'Explosive All-Rounder (86 Runs, 5 Wkts in 4 Matches, SR 209.76)',
    4000,
    'POOLED',
    '{"matches":4,"runs":86,"strikeRate":209.76,"Wickets":5,"economy":14.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Atul Gupta',
    3,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":1,"runs":3,"strikeRate":42.86,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Rahul Lepse',
    3,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":2,"runs":1,"strikeRate":20.00,"Wickets":1,"economy":11.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Nawal Patel',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":5,"runs":27,"strikeRate":84.38,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Ashok Ghuge',
    3,
    NULL,
    'Aggressive Batter (97 Runs, SR 164.41)',
    4000,
    'POOLED',
    '{"matches":9,"runs":97,"strikeRate":164.41,"Wickets":1,"economy":18.50}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Mahesh Shinde',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":7,"runs":68,"strikeRate":119.30,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Ranjit LTI',
    1,
    NULL,
    'High Strike-Rate Batter (193 Runs, SR 167.83)',
    4000,
    'POOLED',
    '{"matches":16,"runs":193,"strikeRate":167.83,"Wickets":0,"economy":15.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Kundan Jha',
    3,
    NULL,
    'Bowling All-Rounder (108 Runs, 12 Wkts)',
    4000,
    'POOLED',
    '{"matches":14,"runs":108,"strikeRate":96.00,"Wickets":12,"economy":8.96}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Abhinandan Gayaki',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":0,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Abhishek Thakur',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":0,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Aditya Shukla',
    3,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":0,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Ajinkya Ambokar',
    2,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":0,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Akhilesh Vilas Dixit',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":4,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Akshay Gavali',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":0,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Amit Kshirsagar',
    3,
    NULL,
    'Explosive All-Rounder (SR 222.22, 2 Wkts, Eco 6.00)',
    4000,
    'POOLED',
    '{"matches":1,"runs":20,"strikeRate":222.22,"Wickets":2,"economy":6.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Atul Kumar Gautam',
    3,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":0,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Bhushan Wagh',
    1,
    NULL,
    'Attacking Batter (91 Runs, SR 126.00)',
    4000,
    'POOLED',
    '{"matches":13,"runs":91,"strikeRate":126.00,"Wickets":2,"economy":9.91}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Dinesh Kumar2',
    2,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":4,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Dinesh Pawar',
    3,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":0,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Dnyaneshwar Misal',
    3,
    NULL,
    'Utility All-Rounder (188 Runs, 4 Wkts)',
    4000,
    'POOLED',
    '{"matches":33,"runs":188,"strikeRate":103.87,"Wickets":4,"economy":8.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Girish Mate',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":1,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Hemant Prakash Raut',
    3,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":0,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Jayesh Ghare',
    3,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":0,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Kedar Dattatray Pegdal',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":0,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Kiran Bagate',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":9,"runs":5,"strikeRate":29.41,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Milind Laxman Kale',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":3,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Mohit Karn',
    3,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":0,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Navjyot Singh',
    2,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":0,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Navnath Kadam',
    3,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":5,"runs":15,"strikeRate":214.00,"Wickets":2,"economy":9.60}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Onkar Lapate',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":0,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Pavan Suresh Warade',
    3,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":0,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Pramod Mhalaskar',
    1,
    NULL,
    'Explosive Batter (261 Runs, SR 174.00)',
    4000,
    'POOLED',
    '{"matches":20,"runs":261,"strikeRate":174.00,"Wickets":12,"economy":10.29}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Prasad Suresh Lotke',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":0,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Rahul Madhav Bodke',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":0,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Ripudaman Singh Bhadoriya',
    3,
    NULL,
    'Economical Strike Bowler (Eco 2.50)',
    4000,
    'POOLED',
    '{"matches":1,"runs":0,"strikeRate":0.00,"Wickets":1,"economy":2.50}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Rohit Shrivastava1',
    2,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":1,"runs":3,"strikeRate":60.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Rushikesh Sable',
    3,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":0,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Rushikesh Shivdas Kshirsagar',
    3,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":0,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Sagar Wankhade',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":0,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Shreyas Shripad Kulkarni',
    2,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":0,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Shubham Katkade',
    1,
    NULL,
    'Attacking Batter (56 Runs, SR 114.00)',
    4000,
    'POOLED',
    '{"matches":7,"runs":56,"strikeRate":114.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Shubham Lamkhade',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":0,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Shubhank Gokhe',
    3,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":0,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Swapnil Tejrao Kale',
    3,
    NULL,
    'Strike All-Rounder (5 Wkts, Eco 8.40)',
    4000,
    'POOLED',
    '{"matches":8,"runs":5,"strikeRate":71.43,"Wickets":5,"economy":8.40}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Takendra Saraswat',
    3,
    NULL,
    'Bowling All-Rounder (11 Wkts, Eco 9.24)',
    4000,
    'POOLED',
    '{"matches":17,"runs":69,"strikeRate":62.73,"Wickets":11,"economy":9.24}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Umesh Sapariya',
    1,
    NULL,
    'Attacking Batter (41 Runs, SR 124.24)',
    4000,
    'POOLED',
    '{"matches":19,"runs":41,"strikeRate":124.24,"Wickets":16,"economy":10.73}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Vaibhav Mhaskar',
    1,
    NULL,
    '',
    4000,
    'POOLED',
    '{"matches":11,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Vilas Kale',
    1,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":4,"runs":1,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Vishal Sanjay Sonawane',
    3,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":0,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Wasim Kanwade',
    3,
    NULL,
    'Wildcard / New Entry',
    4000,
    'POOLED',
    '{"matches":0,"runs":0,"strikeRate":0.00,"Wickets":0,"economy":0.00}',
    0,
    1,
    0,
    'PL-1'
),
(
    'Vivek Chaturvedi',
    3,
    NULL,
    'Attacking Opening Batter (367 Runs, SR 135.33)',
    4000,
    'POOLED',
    '{"matches":37,"runs":367,"strikeRate":135.33,"Wickets":17,"economy":8.78}',
    0,
    1,
    0,
    'PL-1'
);

-- --------------------------------------------------------------------------
-- Step 2: Verification
-- --------------------------------------------------------------------------
SELECT id, playerName, skillId, description, basePrice, groupCode, playerStatus
FROM tblPlayer
WHERE playerStatus = 'POOLED'
ORDER BY id;

SELECT playerStatus, COUNT(*) AS player_count
FROM tblPlayer
GROUP BY playerStatus
ORDER BY playerStatus;
