spring.application.name=auction-service
spring.datasource.url=jdbc:sqlserver://EPINPUNW005D:1433;encrypt=true;trustServerCertificate=true;databaseName=PlayerAuction
spring.datasource.username=sa
spring.datasource.password=admin@123
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server.port=8282